FROM ubuntu:22.04

# This prevents questions during package installations
ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C.UTF-8 LANG=C.UTF-8 TZ=America/New_York

RUN echo deb http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse > /etc/apt/sources.list && \
    echo deb http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse >> /etc/apt/sources.list && \
    echo deb http://ports.ubuntu.com/ubuntu-ports jammy-backports main restricted universe multiverse >> /etc/apt/sources.list && \
    echo deb http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted universe multiverse >> /etc/apt/sources.list && \
    apt-get update -q && \
    apt-get install -qy \
        git \
        wget \
        make \
        autotools-dev \
        autoconf \
        libtool \
        xz-utils \
        libffi-dev \
        libncurses5-dev \
        libsqlite3-dev \
        libusb-1.0-0-dev \
        libudev-dev \
        gettext \
        pkg-config \
        libdbus-1-3 \
        libpcsclite-dev \
        swig \
        libxkbcommon-x11-0 \
        libxcb1 \
        libxcb-icccm4 \
        libxcb-image0 \
        libxcb-keysyms1 \
        libxcb-randr0 \
        libxcb-render-util0 \
        libxcb-render0 \
        libxcb-shape0 \
        libxcb-shm0 \
        libxcb-sync1 \
        libxcb-util1 \
        libxcb-xfixes0 \
        libxcb-xinerama0 \
        libxcb-xkb1 \
        libx11-xcb1 \
        autopoint \
        zlib1g-dev \
        libfreetype6 \
        libfontconfig1 \
        libssl-dev \
        gcc \
        g++ \
        rustc \
        cargo \
        squashfs-tools \
        python3 \
        python3-pip \
        python3-dev \
        python3-venv \
        python3-pyqt5 \
        python3-pyqt5.qtsvg \
        python3-pyqt5.qtmultimedia \
        qt5-qmake \
        qtbase5-dev \
        qttools5-dev \
        qttools5-dev-tools \
        libqt5svg5-dev \
        python3-sip-dev \
        python3-sip \
        && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean

# This is to enable nightly features in the release configuration
ENV RUSTC_BOOTSTRAP=1
# Enable trim-paths feature in cargo 1.75+ to make sure pip paths
# do not end up in binaries making them not reproducible
ENV CARGO_TRIM_PATHS=all
ENV CARGO_UNSTABLE_TRIM_PATHS=true
